### ISSUE TITLE
Iteração 0 - Ajustes no README.md

### ISSUE THREAD

**Issue by mpocin** [amandatrigueiro/ConchaCultural#3]
Falta as seguintes informações no arquivo README.md:
Características do projeto;
Especificação do papel de cada membro da equipe;
Outras informações pertinentes.

**Comment by mpocin** [comment]
ainda falta informações sobre a descrição do problema e como o projeto vai resolver o problema.

**Comment by JhonattasFerreira** [comment]
Descriçoes e objetivos adicionados, obrigado
